const products = [
  {
    sku: "BDIAP001",
    name: "Baby Diapers",
    description: "Soft and comfortable diapers for babies.",
    slug: "baby-diapers",
    category: "62cc0791d511b304aecdfbf2",
    image: "https://i.ibb.co/XkZxK0Hk/Baby-Care-s2xjj8.png",
    prices: {
      originalPrice: 20,
      price: 15,
      discount: 0,
    },
    quantity: 200,
    expiryDate: "2026-01-01T00:00:00.000Z",
    tag: ["Baby Care", "Diapers"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "BSHMP002",
    name: "Baby Shampoo",
    description: "Gentle shampoo for babies with a soothing fragrance.",
    slug: "baby-shampoo",
    category: "62cc0791d511b304aecdfbf2",
    image: "https://i.ibb.co/XkZxK0Hk/Baby-Care-s2xjj8.png",
    prices: {
      originalPrice: 15,
      price: 10,
      discount: Math.floor(Math.random() * 30) + 5,
    },
    quantity: 300,
    expiryDate: "2026-06-01T00:00:00.000Z",
    tag: ["Baby Care", "Shampoo"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "BLOTN003",
    name: "Baby Lotion",
    description: "Moisturizing lotion for delicate baby skin.",
    slug: "baby-lotion",
    category: "62cc0791d511b304aecdfbf2",
    image: "https://i.ibb.co/XkZxK0Hk/Baby-Care-s2xjj8.png",
    prices: {
      originalPrice: 18,
      price: 12,
      discount: 0,
    },
    quantity: 150,
    expiryDate: "2027-01-01T00:00:00.000Z",
    tag: ["Baby Care", "Lotion"],
    status: "show",
    requiresPrescription: true,
  },
  {
    sku: "FCLEAN004",
    name: "Face Cleanser",
    description: "A gentle facial cleanser for everyday use.",
    slug: "face-cleanser",
    category: "62cfab28484d89068aa7a7f5",
    image: "https://i.ibb.co/35Wg3Yks/Face-and-skin-care-b3slrz.png",
    prices: {
      originalPrice: 25,
      price: 20,
      discount: Math.floor(Math.random() * 20) + 10,
    },
    quantity: 250,
    expiryDate: "2026-09-01T00:00:00.000Z",
    tag: ["Face Care", "Cleanser"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "MCREAM005",
    name: "Moisturizing Cream",
    description: "Rich cream that provides deep moisture to the skin.",
    slug: "moisturizing-cream",
    category: "62cfab28484d89068aa7a7f5",
    image: "https://i.ibb.co/35Wg3Yks/Face-and-skin-care-b3slrz.png",
    prices: {
      originalPrice: 30,
      price: 25,
      discount: 0,
    },
    quantity: 0,
    expiryDate: "2027-03-01T00:00:00.000Z",
    tag: ["Face Care", "Moisturizer"],
    status: "show",
    requiresPrescription: true,
  },
  {
    sku: "SUNSPF006",
    name: "Sunscreen SPF 30",
    description: "Protects your skin from harmful UV rays.",
    slug: "sunscreen-spf-30",
    category: "62cfab28484d89068aa7a7f5",
    image: "https://i.ibb.co/35Wg3Yks/Face-and-skin-care-b3slrz.png",
    prices: {
      originalPrice: 22,
      price: 18,
      discount: 0,
    },
    quantity: 220,
    expiryDate: "2026-07-01T00:00:00.000Z",
    tag: ["Face Care", "Sunscreen"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "SPADS007",
    name: "Sanitary Pads",
    description: "Comfortable and reliable sanitary pads.",
    slug: "sanitary-pads",
    category: "62cfab39484d89068aa7a7fb",
    image: "https://i.ibb.co/LdP2cq6M/Feminine-hygiene-v7gan7.png",
    prices: {
      originalPrice: 8,
      price: 6,
      discount: Math.floor(Math.random() * 15) + 10,
    },
    quantity: 500,
    expiryDate: "2026-01-01T00:00:00.000Z",
    tag: ["Feminine Hygiene", "Pads"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "FWIPE008",
    name: "Feminine Wipes",
    description: "Wipes for maintaining hygiene during menstruation.",
    slug: "feminine-wipes",
    category: "62cfab39484d89068aa7a7fb",
    image: "https://i.ibb.co/LdP2cq6M/Feminine-hygiene-v7gan7.png",
    prices: {
      originalPrice: 10,
      price: 8,
      discount: 0,
    },
    quantity: 300,
    expiryDate: "2027-01-01T00:00:00.000Z",
    tag: ["Feminine Hygiene", "Wipes"],
    status: "show",
    requiresPrescription: true,
  },
  {
    sku: "MCUPS009",
    name: "Menstrual Cups",
    description: "Reusable menstrual cups for feminine hygiene.",
    slug: "menstrual-cups",
    category: "62cfab39484d89068aa7a7fb",
    image: "https://i.ibb.co/LdP2cq6M/Feminine-hygiene-v7gan7.png",
    prices: {
      originalPrice: 15,
      price: 12,
      discount: Math.floor(Math.random() * 20) + 5,
    },
    quantity: 150,
    expiryDate: "2026-06-01T00:00:00.000Z",
    tag: ["Feminine Hygiene", "Menstrual Cup"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "FAIDK010",
    name: "First Aid Kit",
    description: "Complete first aid kit with all essentials.",
    slug: "first-aid-kit",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 35,
      price: 30,
      discount: 0,
    },
    quantity: 100,
    expiryDate: "2027-01-01T00:00:00.000Z",
    tag: ["First Aid", "Emergency"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "BRELF011",
    name: "Burn Relief Gel",
    description: "Gel for treating burns and soothing the skin.",
    slug: "burn-relief-gel",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 20,
      price: 15,
      discount: Math.floor(Math.random() * 20) + 5,
    },
    quantity: 150,
    expiryDate: "2026-09-01T00:00:00.000Z",
    tag: ["First Aid", "Burn Relief"],
    status: "show",
    requiresPrescription: true,
  },
  {
    sku: "ANTST012",
    name: "Antiseptic Solution",
    description: "Antiseptic solution for cleaning wounds.",
    slug: "antiseptic-solution",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 12,
      price: 10,
      discount: 0,
    },
    quantity: 0,
    expiryDate: "2026-12-01T00:00:00.000Z",
    tag: ["First Aid", "Antiseptic"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "VITC001",
    name: "Vitamin C Tablets",
    description: "Boost your immune system with Vitamin C.",
    slug: "vitamin-c-tablets",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 15,
      price: 12,
      discount: Math.floor(Math.random() * 15),
    },
    quantity: 300,
    expiryDate: "2027-02-15T00:00:00.000Z",
    tag: ["Vitamins", "Supplements"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "PAINR002",
    name: "Pain Relief Tablets",
    description: "Effective pain relief for headaches and body aches.",
    slug: "pain-relief-tablets",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 10,
      price: 8,
      discount: 0,
    },
    quantity: 250,
    expiryDate: "2026-11-30T00:00:00.000Z",
    tag: ["Pain Relief", "Medication"],
    status: "show",
    requiresPrescription: true,
  },
  {
    sku: "COUGH003",
    name: "Cough Syrup",
    description: "Relieves cough and soothes sore throats.",
    slug: "cough-syrup",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 12,
      price: 10,
      discount: Math.floor(Math.random() * 10) + 5,
    },
    quantity: 180,
    expiryDate: "2026-10-01T00:00:00.000Z",
    tag: ["Cough", "Syrup"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "BANDG004",
    name: "Bandages",
    description: "Adhesive bandages for minor cuts and scrapes.",
    slug: "bandages",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 7,
      price: 5,
      discount: 0,
    },
    quantity: 400,
    expiryDate: "2027-03-15T00:00:00.000Z",
    tag: ["First Aid", "Bandages"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "HANDS005",
    name: "Hand Sanitizer",
    description: "Kills germs and bacteria on your hands.",
    slug: "hand-sanitizer",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 8,
      price: 6,
      discount: Math.floor(Math.random() * 12),
    },
    quantity: 350,
    expiryDate: "2026-09-30T00:00:00.000Z",
    tag: ["Hygiene", "Sanitizer"],
    status: "show",
    requiresPrescription: false,
  },
  {
    sku: "MASKF006",
    name: "Face Masks",
    description: "Protective masks to prevent the spread of germs.",
    slug: "face-masks",
    category: "62cfab4b484d89068aa7a7ff",
    image: "https://i.ibb.co/DPQKpjy5/First-Aid-Kit-xnevd2.png",
    prices: {
      originalPrice: 10,
      price: 7,
      discount: 0,
    },
    quantity: 500,
    expiryDate: "2027-01-31T00:00:00.000Z",
    tag: ["Hygiene", "Face Masks"],
    status: "show",
    requiresPrescription: false,
  },
];

module.exports = products;
