const cityShippingData = [
  { name: "Colombo", cost: 100 },
  { name: "Gampaha", cost: 90 },
  { name: "Kalutara", cost: 100 },
  { name: "Kandy", cost: 90 },
  { name: "Matale", cost: 85 },
  { name: "Nuwara Eliya", cost: 95 },
  { name: "Galle", cost: 110 },
  { name: "Matara", cost: 115 },
  { name: "Hambantota", cost: 120 },
  { name: "Jaffna", cost: 130 },
  { name: "Kilinochchi", cost: 135 },
  { name: "Mannar", cost: 125 },
  { name: "Vavuniya", cost: 120 },
  { name: "Mullaitivu", cost: 140 },
  { name: "Batticaloa", cost: 125 },
  { name: "Ampara", cost: 115 },
  { name: "Trincomalee", cost: 120 },
  { name: "Kurunegala", cost: 80 },
  { name: "Puttalam", cost: 100 },
  { name: "Anuradhapura", cost: 110 },
  { name: "Polonnaruwa", cost: 105 },
  { name: "Badulla", cost: 100 },
  { name: "Monaragala", cost: 115 },
  { name: "Ratnapura", cost: 95 },
  { name: "Kegalle", cost: 90 },
];

export default cityShippingData;
